import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Information | MirrorSource",
};

export default function LegalPage() {
  return (
    <main className="min-h-screen bg-slate-50 flex flex-col">
      <div className="flex-1 py-16 px-4">
        <div className="mx-auto max-w-3xl rounded-xl bg-white p-8 shadow border border-slate-200 space-y-8">
        
          {/* CLICKABLE LOGO HEADER */}
          <div className="flex justify-center pb-4 border-b border-slate-100">
            <Link href="/" className="hover:opacity-80 transition-opacity">
              <Image 
                src="/logo.png" 
                alt="MirrorSource" 
                width={200} 
                height={50} 
                className="h-auto w-auto"
              />
            </Link>
          </div>

          <header className="space-y-2 text-center sm:text-left">
            <h1 className="text-3xl font-bold text-slate-900">Legal Information</h1>
            <p className="text-sm text-slate-500">Effective Date: 2025-01-12</p>
            <p className="text-slate-700">
              This page contains all legal notices, policies, and terms that govern the use of the MirrorSource website and services.
            </p>
          </header>

          {/* 1. Terms of Use */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">1. Terms of Use</h2>

            <h3 className="text-lg font-semibold text-slate-900">About MirrorSource</h3>
            <p className="text-slate-700">
              MirrorSource provides computer-generated summaries and alternative source suggestions based on publicly available information. MirrorSource does not reproduce full articles or paywalled content. MirrorSource does not store or distribute copyrighted materials.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Your Responsibilities</h3>
            <p className="text-slate-700">
              You agree to use MirrorSource only for lawful purposes, and you will not attempt to bypass paywalls or technical protections, access restricted content, scrape websites, or use the service in ways that infringe the rights of others.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">No Professional Advice</h3>
            <p className="text-slate-700">
              Content generated by MirrorSource is informational only. It is not legal, financial, or medical advice.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Intellectual Property</h3>
            <p className="text-slate-700">
              All original content on MirrorSource is owned by MirrorSource or its licensors. You may not copy, republish, or commercially exploit MirrorSource content without permission.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Third-Party Websites</h3>
            <p className="text-slate-700">
              MirrorSource may display links to external websites, including partner and affiliate links. MirrorSource does not control those sites, and is not responsible for their content, policies, or practices.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Service Availability</h3>
            <p className="text-slate-700">
              The service is provided on an &apos;as is&apos; and &apos;as available&apos; basis.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Limitation of Liability</h3>
            <p className="text-slate-700">
              To the maximum extent permitted by law, MirrorSource is not liable for any indirect, incidental, consequential, or special damages that arise from the use of or inability to use the service.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Changes to These Terms</h3>
            <p className="text-slate-700">
              MirrorSource may update these Terms. Continued use means you accept the changes. If you do not agree, stop using the service.
            </p>
          </section>

          {/* 2. Privacy Policy */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">2. Privacy Policy</h2>

            <h3 className="text-lg font-semibold text-slate-900">Information We Collect</h3>
            <p className="text-slate-700 mb-2">
              MirrorSource collects minimal data. This includes:
            </p>
            <p className="text-slate-700 mb-1">
              <strong>Technical Information:</strong> IP address, browser type, device information.
            </p>
            <p className="text-slate-700 mb-1">
              <strong>Usage Data:</strong> Pages visited, queries submitted, Intel Briefs generated.
            </p>
            <p className="text-slate-700">
              <strong>Personal Information:</strong> Personal information is collected when you create an account, subscribe to updates, request an Intel Brief, or contact us directly. This typically includes your email address and any preferences you set.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">How We Use Information</h3>
            <p className="text-slate-700 mb-2">
              We use information to:
            </p>
            <ul className="list-disc pl-6 text-slate-700 space-y-1">
              <li>Operate and improve the service</li>
              <li>Diagnose issues and prevent misuse</li>
              <li>Monitor performance</li>
              <li>Send you service notifications (e.g., login links, security alerts)</li>
              <li>Send product updates or newsletters (only if you have explicitly opted in)</li>
            </ul>
            <p className="text-slate-700 mt-2">
              MirrorSource does not sell or rent your information.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Cookies</h3>
            <p className="text-slate-700">
              MirrorSource uses cookies only as described in the Cookie Notice. You can control cookies in your browser settings.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Third-Party Providers</h3>
            <p className="text-slate-700">
              We may use hosting, analytics, or email delivery providers. They process technical data on our behalf.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Data Security</h3>
            <p className="text-slate-700">
              We take reasonable steps to protect data. No system is perfectly secure.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Changes to This Policy</h3>
            <p className="text-slate-700">
              We may update this Privacy Policy. The latest version is always on this page.
            </p> 
          </section>

          {/* 3. Cookie Notice */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">3. Cookie Notice</h2>
            <p className="text-slate-700">
              MirrorSource uses essential cookies to operate the website and improve user experience. Continuing to use the site means you consent to these cookies.
            </p>
          </section>

          {/* 4. DMCA Policy */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">4. DMCA Policy</h2>
            <p className="text-slate-700">
              MirrorSource respects the intellectual property rights of authors and publishers.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Reporting Copyright Infringement</h3>
            <p className="text-slate-700">
              To report alleged infringement, submit a DMCA notice via the contact email listed at the end of this document. Include:
            </p>
            <ul className="list-disc pl-6 text-slate-700 space-y-1">
              <li>Your name and contact information.</li>
              <li>Identification of the copyrighted work.</li>
              <li>Identification of the material you believe is infringing and where it appears.</li>
              <li>A good faith statement that the use is not authorized.</li>
              <li>An accuracy statement and your signature or typed name.</li>
            </ul>

            <h3 className="text-lg font-semibold text-slate-900">Counter Notification</h3>
            <p className="text-slate-700">
              If you believe material was removed by mistake, submit a counter notice via the contact email listed at the end of this document. Include your contact details, a statement under penalty of perjury that the removal was a mistake or misidentification, consent to court jurisdiction, and your signature.
            </p>
          </section>

          {/* 5. GDPR Addendum */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">5. GDPR Addendum (EU and UK Users)</h2>

            <h3 className="text-lg font-semibold text-slate-900">Your Rights</h3>
            <p className="text-slate-700">
              Subject to law, you may request access, correction, deletion, restriction, or a portable copy of your data via the contact email provided at the end of this document.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Legal Basis</h3>
            <p className="text-slate-700 mb-2">
              Processing of limited technical data is based on legitimate interests in operating and securing the service.
            </p>
            <p className="text-slate-700">
              For email communications, processing is based on your consent, which you may withdraw at any time by unsubscribing or contacting us.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Data Transfers</h3>
            <p className="text-slate-700">
              Your data may be processed outside the EU or UK. Use of the service implies consent to such transfers where lawful.
            </p>
          </section>

          {/* 6. Accessibility */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">6. Accessibility Statement</h2>
            <p className="text-slate-700">
              If you encounter difficulty using any part of the site or require an accommodation, please contact us using the email provided below.
            </p>
          </section>

          {/* 7. Do Not Sell or Share My Data */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">7. Do Not Sell or Share My Data</h2>
            <p className="text-slate-700">
              MirrorSource does not sell or share personal information. California residents may request confirmation via the contact email provided below.
            </p>
          </section>

          {/* 8. Contact and Legal Requests */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">8. Contact and Legal Requests</h2>
            <p className="text-slate-700">
              For privacy questions, DMCA notices, security concerns, or other legal matters, please refer to the official contact email below.
            </p>
          </section>

          {/* 9. Security Disclosure */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">9. Security Disclosure</h2>
            <p className="text-slate-700">
              Report vulnerabilities via the contact email. Include a description and steps to reproduce. Please avoid public disclosure before we respond.
            </p>
          </section>

          {/* 10. Anti-Scraping and Abuse */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">10. Anti-Scraping and Abuse</h2>
            <p className="text-slate-700">
              Personal use only. No bots, scripts, automated tools, or bulk requests. No reverse engineering or harvesting of data. We may block or suspend access for abusive behavior.
            </p>
          </section>

          {/* 11. Legal Disclaimer */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">11. Legal Disclaimer</h2>
            <p className="text-slate-700">
              MirrorSource summaries are generated by automated systems and may contain errors. MirrorSource provides AI-generated summaries for information only. MirrorSource does not provide legal, financial, or professional advice. All trademarks and copyrights belong to their respective owners.
            </p>
          </section>

          {/* 12. Affiliate Disclosure */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">12. Affiliate Disclosure</h2>
            <p className="text-slate-700">
              MirrorSource may display recommendations for third-party products and services. Some links are affiliate links, meaning MirrorSource may earn a commission if you make a purchase. This does not affect the price you pay. We only recommend tools that align with our values of transparency, privacy, and user agency.
            </p>
          </section>

          {/* 13. Email Communications */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">13. Email Communications</h2>
            <p className="text-slate-700">
              If you provide your email address to access additional features or receive updates, we will use it solely to:
            </p>
            <ul className="list-disc pl-6 text-slate-700 space-y-1">
              <li><strong>Service notifications:</strong> Account verification, login links, security alerts, and important service updates.</li>
              <li><strong>Product updates and newsletters:</strong> Only if you explicitly opt in during signup.</li>
            </ul>

            <h3 className="text-lg font-semibold text-slate-900">Unsubscribe</h3>
            <p className="text-slate-700">
              You may unsubscribe from marketing emails at any time by clicking the &quot;unsubscribe&quot; link in the footer of any email, or by contacting us directly.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">No Spam</h3>
            <p className="text-slate-700">
              We do not sell, rent, or trade email addresses with third parties for marketing purposes.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Service Providers</h3>
            <p className="text-slate-700">
              We use third-party providers (such as Resend or Supabase) to manage email storage and delivery. Your email address may be processed by these providers in accordance with their respective privacy policies.
            </p>
          </section>

          {/* 14. Canadian Anti-Spam Law (CASL) Notice */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">14. Canadian Anti-Spam Law (CASL) Notice</h2>
            <p className="text-slate-700">
              If you are located in Canada, we comply with the Canadian Anti-Spam Legislation. We will only send commercial electronic messages with your express consent. You may withdraw consent at any time using the unsubscribe mechanism provided.
            </p>
          </section>

          {/* OFFICIAL CONTACT FOOTER */}
          <div className="mt-12 pt-8 border-t border-slate-200 text-center">
            <p className="text-slate-900 font-medium">For all legal, privacy, and support inquiries:</p>
            <Link 
              href="/contact"
              className="text-blue-600 font-semibold text-lg hover:underline mt-2 block"
            >
              Contact Us →
            </Link>
          </div>

        </div>
      </div>

      {/* Footer */}
      <footer className="py-6 px-4 border-t border-slate-200 bg-white mt-auto">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-slate-500">
          <p>&copy; {new Date().getFullYear()} MirrorSource</p>
          <div className="flex items-center gap-6">
            <Link href="/about" className="hover:text-blue-600 transition-colors">About</Link>
            <Link href="/sources" className="hover:text-blue-600 transition-colors">Sources</Link>
            <Link href="/legal" className="hover:text-blue-600 transition-colors">Legal</Link>
            <Link href="/contact" className="hover:text-blue-600 transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}