import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Legal Information | MirrorSource",
};

export default function LegalPage() {
  return (
    <main className="min-h-screen bg-slate-50 flex flex-col">
      <div className="flex-1 py-16 px-4">
        <div className="mx-auto max-w-3xl rounded-xl bg-white p-8 shadow border border-slate-200 space-y-8">
        
          {/* CLICKABLE LOGO HEADER */}
          <div className="flex justify-center pb-4 border-b border-slate-100">
            <Link href="/" className="hover:opacity-80 transition-opacity">
              <Image 
                src="/logo.png" 
                alt="MirrorSource" 
                width={200} 
                height={50} 
                className="h-auto w-auto"
              />
            </Link>
          </div>

          <header className="space-y-2 text-center sm:text-left">
            <h1 className="text-3xl font-bold text-slate-900">Legal Information</h1>
            <p className="text-sm text-slate-500">Effective Date: 2025-11-20</p>
            <p className="text-slate-700">
              This page contains all legal notices, policies, and terms that govern the use of the MirrorSource website and services.
            </p>
          </header>

          {/* 1. Terms of Use */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">1. Terms of Use</h2>

            <h3 className="text-lg font-semibold text-slate-900">About MirrorSource</h3>
            <p className="text-slate-700">
              MirrorSource provides computer-generated summaries and alternative source suggestions based on publicly available information. MirrorSource does not reproduce full articles or paywalled content. MirrorSource does not store or distribute copyrighted materials.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Your Responsibilities</h3>
            <p className="text-slate-700">
              You agree to use MirrorSource only for lawful purposes, and you will not attempt to bypass paywalls or technical protections, access restricted content, scrape websites, or use the service in ways that infringe the rights of others.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">No Professional Advice</h3>
            <p className="text-slate-700">
              Content generated by MirrorSource is informational only. It is not legal, financial, or medical advice.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Intellectual Property</h3>
            <p className="text-slate-700">
              All original content on MirrorSource is owned by MirrorSource or its licensors. You may not copy, republish, or commercially exploit MirrorSource content without permission.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Third-Party Websites</h3>
            <p className="text-slate-700">
              MirrorSource may display links to external websites. MirrorSource does not control those sites, and is not responsible for their content, policies, or practices.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Service Availability</h3>
            <p className="text-slate-700">
              The service is provided on an 'as is' and 'as available' basis.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Limitation of Liability</h3>
            <p className="text-slate-700">
              To the maximum extent permitted by law, MirrorSource is not liable for any indirect, incidental, consequential, or special damages that arise from the use of or inability to use the service.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Changes to These Terms</h3>
            <p className="text-slate-700">
              MirrorSource may update these Terms. Continued use means you accept the changes. If you do not agree, stop using the service.
            </p>
          </section>

          {/* 2. Privacy Policy */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">2. Privacy Policy</h2>

            <h3 className="text-lg font-semibold text-slate-900">Information We Collect</h3>
            <p className="text-slate-700">
              MirrorSource collects minimal data. This includes technical information such as IP address, browser type, device information, and usage data such as pages visited or queries submitted. Personal information is collected only if you provide it by contacting us directly.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">How We Use Information</h3>
            <p className="text-slate-700">
              We use information to operate and improve the service, diagnose issues, prevent misuse, and monitor performance. MirrorSource does not sell or rent your information.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Cookies</h3>
            <p className="text-slate-700">
              MirrorSource uses cookies only as described in the Cookie Notice. You can control cookies in your browser settings.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Third-Party Providers</h3>
            <p className="text-slate-700">
              We may use hosting or analytics providers. They process technical data on our behalf.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Data Security</h3>
            <p className="text-slate-700">
              We take reasonable steps to protect data. No system is perfectly secure.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Changes to This Policy</h3>
            <p className="text-slate-700">
              We may update this Privacy Policy. The latest version is always on this page.
            </p> 
          </section>

          {/* 3. Cookie Notice */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">3. Cookie Notice</h2>
            <p className="text-slate-700">
              MirrorSource uses essential cookies to operate the website and improve user experience. Continuing to use the site means you consent to these cookies.
            </p>
          </section>

          {/* 4. DMCA Policy */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">4. DMCA Policy</h2>
            <p className="text-slate-700">
              MirrorSource respects the intellectual property rights of authors and publishers.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Reporting Copyright Infringement</h3>
            <p className="text-slate-700">
              To report alleged infringement, submit a DMCA notice via the contact email listed at the end of this document. Include:
            </p>
            <ul className="list-disc pl-6 text-slate-700 space-y-1">
              <li>Your name and contact information.</li>
              <li>Identification of the copyrighted work.</li>
              <li>Identification of the material you believe is infringing and where it appears.</li>
              <li>A good faith statement that the use is not authorized.</li>
              <li>An accuracy statement and your signature or typed name.</li>
            </ul>

            <h3 className="text-lg font-semibold text-slate-900">Counter Notification</h3>
            <p className="text-slate-700">
              If you believe material was removed by mistake, submit a counter notice via the contact email listed at the end of this document. Include your contact details, a statement under penalty of perjury that the removal was a mistake or misidentification, consent to court jurisdiction, and your signature.
            </p>
          </section>

          {/* 5. GDPR Addendum */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">5. GDPR Addendum (EU and UK Users)</h2>

            <h3 className="text-lg font-semibold text-slate-900">Your Rights</h3>
            <p className="text-slate-700">
              Subject to law, you may request access, correction, deletion, restriction, or a portable copy of your data via the contact email provided at the end of this document.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Legal Basis</h3>
            <p className="text-slate-700">
              Processing of limited technical data is based on legitimate interests in operating and securing the service.
            </p>

            <h3 className="text-lg font-semibold text-slate-900">Data Transfers</h3>
            <p className="text-slate-700">
              Your data may be processed outside the EU or UK. Use of the service implies consent to such transfers where lawful.
            </p>
          </section>

          {/* 6. Accessibility */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">6. Accessibility Statement</h2>
            <p className="text-slate-700">
              If you encounter difficulty using any part of the site or require an accommodation, please contact us using the email provided below.
            </p>
          </section>

          {/* 7. Do Not Sell or Share My Data */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">7. Do Not Sell or Share My Data</h2>
            <p className="text-slate-700">
              MirrorSource does not sell or share personal information. California residents may request confirmation via the contact email provided below.
            </p>
          </section>

          {/* 8. Contact and Legal Requests */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">8. Contact and Legal Requests</h2>
            <p className="text-slate-700">
              For privacy questions, DMCA notices, security concerns, or other legal matters, please refer to the official contact email below.
            </p>
          </section>

          {/* 9. Security Disclosure */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">9. Security Disclosure</h2>
            <p className="text-slate-700">
              Report vulnerabilities via the contact email. Include a description and steps to reproduce. Please avoid public disclosure before we respond.
            </p>
          </section>

          {/* 10. Anti-Scraping and Abuse */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">10. Anti-Scraping and Abuse</h2>
            <p className="text-slate-700">
              Personal use only. No bots, scripts, automated tools, or bulk requests. No reverse engineering or harvesting of data. We may block or suspend access for abusive behavior.
            </p>
          </section>

          {/* 11. Legal Disclaimer */}
          <section className="space-y-3">
            <h2 className="text-2xl font-semibold text-slate-900">11. Legal Disclaimer</h2>
            <p className="text-slate-700">
              MirrorSource summaries are generated by automated systems and may contain errors. MirrorSource provides AI-generated summaries for information only. MirrorSource does not provide legal, financial, or professional advice. All trademarks and copyrights belong to their respective owners.
            </p>
          </section>

          {/* OFFICIAL CONTACT FOOTER */}
          <div className="mt-12 pt-8 border-t border-slate-200 text-center">
            <p className="text-slate-900 font-medium">For all legal, privacy, and support inquiries:</p>
            <Link 
              href="/contact"
              className="text-[#2563eb] font-semibold text-lg hover:underline mt-2 block"
            >
              Contact Us →
            </Link>
          </div>

        </div>
      </div>

      {/* Footer */}
      <footer className="py-6 px-4 border-t border-slate-200 bg-white mt-auto">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-slate-500">
          <p>&copy; {new Date().getFullYear()} MirrorSource</p>
          <div className="flex items-center gap-6">
            <Link href="/about" className="hover:text-[#2563eb] transition-colors">About</Link>
            <Link href="/sources" className="hover:text-[#2563eb] transition-colors">Sources</Link>
            <Link href="/legal" className="hover:text-[#2563eb] transition-colors">Legal</Link>
            <Link href="/contact" className="hover:text-[#2563eb] transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </main>
  );
}